In [67]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as sla 

### Задача 1. (1 балл)

Сделайте задания ниже, используя библиотеки numpy и/или scipy.

1. Найдите определитель матрицы

$$ \begin{pmatrix} 1 & 6 & 4 & 2 & 4 \\ 4 & 3 & 1 & 34 & 1 \\ 45 & 4 & 1 & 3 & 4 \\ 12 & 7 & 11 & 2 & 0 \\ 43 & 42 & 10 & 1 & 2 \end{pmatrix}$$

In [68]:
a1 = np.array([[1, 6, 4, 2, 4],
              [4, 3, 1, 34, 1],
              [45, 4, 1, 3, 4],
              [12, 7, 11, 2, 0],
              [43, 42, 10, 1, 2]])

In [69]:
np.linalg.det(a1) # round(np.linalg.det(a)) # 2366669

2366668.9999999986

2. Найдите матрицу, обратную матрице

$$ \begin{pmatrix} 1 & 12 & 3 & 2 \\ 4 & 30 & 0 & 1 \\ 12 & 4 & 3 & 5 \\ 1 & 5 & 1 & 10  \end{pmatrix}$$


In [70]:
a2 = np.array([[1, 12, 3, 2],
              [4, 30, 0, 1],
              [12, 4, 3, 5],
              [1, 5, 1, 10]])

In [71]:
np.linalg.inv(a2)

array([[-7.43236448e-02,  2.34335714e-02,  8.41798250e-02,
        -2.95685407e-02],
       [ 1.09624862e-02,  3.03731268e-02, -1.10630594e-02,
         3.01719803e-04],
       [ 3.35311274e-01, -1.26018304e-01,  1.94106407e-02,
        -6.41657447e-02],
       [-3.15800060e-02, -4.92809011e-03, -4.82751685e-03,
         1.09222569e-01]])

3. Найдите собственные значения матрицы
$$ \begin{pmatrix} 1 & 10 & 3 & 12 \\ 3 & 20 & 0 & 2 \\ 11 & 3 & 3 & 6 \\ 1 & 8 & 1 & 10   \end{pmatrix}$$


In [72]:
a3 = np.array([[1, 12, 3, 2],
              [4, 30, 0, 1],
              [12, 4, 3, 5],
              [1, 5, 1, 10]])

In [73]:
np.linalg.eig(a3)[0]

array([32.0200691 , -4.82133249,  5.91782057, 10.88344282])

4. Найдите спектральное разложение матрицы

$$ \begin{pmatrix} 1 & 10 & 3 & 12 \\ 3 & 20 & 0 & 2 \\ 11 & 3 & 3 & 6 \\ 1 & 8 & 1 & 10   \end{pmatrix}$$

In [74]:
a4 = np.array([[1, 10, 3, 12],
              [3, 20, 0, 2],
              [11, 3, 3, 6],
              [1, 8, 1, 10]])

In [75]:
q, r =  np.linalg.qr(a4) 

In [76]:
print('Q:\n', q, '\n\nR:\n', r)

Q:
 [[-0.08703883 -0.41820193  0.84887995 -0.31134261]
 [-0.26111648 -0.79800814 -0.49877128 -0.2150079 ]
 [-0.95742711  0.28537352  0.04344524  0.00279231]
 [-0.08703883 -0.3268824   0.16953629  0.9256509 ]] 

R:
 [[-11.48912529  -9.66130991  -3.22043664  -8.18164983]
 [  0.         -21.90112077  -0.72536761  -8.17102227]
 [  0.           0.           2.84651185  11.14505118]
 [  0.           0.           0.           5.10713572]]


### Задача 2 (0.5)

Рассмотрим задачу:

Сколько существует 5-значных чисел, которые начинаются с цифры 2 или 4, содержат только четные цифры и при этом каждая цифра повторяется не более трёх раз?

1. Приведите "математическое" решение этой задачи. (0.1).
2. Напишите код на python, который перебирает все числа, проверяет, удовлетворяют ли они условию и в конце выводит количество нужных чисел. (0.4)

In [77]:
# 1.Приведите "математическое" решение этой задачи. (0.1).

0, 2, 4, 6, 8 - 5 четных чисел

In [78]:
2 * 5 * 5 * 4 * 4

800

In [79]:
# 2.Напишите код на python, который перебирает все числа, проверяет, удовлетворяют ли они условию и в конце выводит количество нужных чисел. (0.4)

In [80]:
count_of_numbers = 0
lst = []

for i in range(20000, 88867):
    number = str(i)
    count_n = Counter(number)
    
    if any(count > 3 for count in count_n.values()):
        continue
    else:
        a1 = int(number[0])
        a2 = int(number[1])
        a3 = int(number[2])
        a4 = int(number[3])
        a5 = int(number[4])
        
        if a1 in [2, 4]:
            if a2 in [0, 2, 4, 6, 8]:
                if a3 in [0, 2, 4, 6, 8]:
                    if a4 in [0, 2, 4, 6, 8]:
                        if a5 in [0, 2, 4, 6, 8]:
                            count_of_numbers += 1
                            lst.append(number)
                        else:
                            continue
                    else:
                        continue
                else:
                    continue
            else:
                continue
        else:
            continue
            
print(count_of_numbers)

1208


In [81]:
max(lst)

'48886'

### Задача 3 (1 балл)


*Это задача на "отлично (превосходит ожидания)" по шкале перевода оценок НИУ ВШЭ:  https://www.hse.ru/studyspravka/Scale*

*Но она на самом деле не такая уж сложная.*



a. (0.8). Напишите свою функцию-реализацию метода Гаусса для решения систем линейных уравнений.

Программа должна принимать на вход Матрицу A и вектор-столбец b и решать систему уравнений $Ax=b$.

Вы можете самостотельно определить формат входных и выходных данных. Например, вы можете хранить A как двумерный numpy массив A или список списков, вектор-столбец b - как одномерный numpy-массив или список (list). Программа должна возвращать вектор x. Отдельно подумайте над ситуациями, когда решений нет или бесконечно много.

Разрешено использовать numpy, но только для операций над массивами (нельзя использовать numpy.linalg, за исключением numpy.linalg.det, если понадобится).

b. (0.2).Напишите свою функцию-реализацию метода Крамера для решения систем линейных уравнений.

Все дополнительные условия - как в п.а. Если система не может быть решена методом Крамера, функция должна вывести соответствующее сообщение.



### Задача 4 (1 балл)

*Это задача на "отлично (существенно превосходит ожидания)" по шкале перевода оценок НИУ ВШЭ:  https://www.hse.ru/studyspravka/Scale*.

*Даже из команды курса за неё не все готовы были бы взяться.*

Система может находиться в одном из двух состояний $A$ или $B$. Экспериментатор умеет измерять косвенную величину $x$, которая поможет ему определить состояние, в котором находится система. Тем не менее, метод, которым экспериментатор измеряет величину $x$ обладает погрешностью. Будем считать, что функция распределения величины $x$ имеет гауссов вид, причем среднее значение равно $\pm \tilde x$ для состояний $A$ и $B$ соответственно, а дисперсия равна $\sigma^2$ и не зависит от состояния:

\begin{equation}
  P(x\ |\ A) = \frac{1}{\sqrt{2 \pi \sigma}}\exp\left(\frac{-(x-\tilde x)^2}{2 \sigma^2}\right), \quad P(x\ |\ B) = \frac{1}{\sqrt{2 \pi \sigma}}\exp\left(\frac{-(x+\tilde x)^2}{2 \sigma^2}\right).
\end{equation}

В случае, когда $\sigma \gg \tilde x$ погрешность метода слишком велика и отдельное измерение не позволяет достоверно определить состояние, в котором находится система. Пусть $\tilde x = 1$, $\sigma = 10$ и каждое измерение не изменяет состояния системы. Предлагается выполнить $N$ измерений, чтобы определить состояние системы.

In [ ]:
X_MEAN = 1
SIGMA = 10

1. (0.3 Балла) Пусть априорные вероятности нахождения системы в состояниях A и B равны друг другу, $P(A) = P(B) = 1/2$. Сгенерируйте состояние системы, а затем проведите $N$ измерений величины $x$ в соотвествии с вероятностями, приведенными выше, получится массив $\{x_1,x_2, \dots, x_N\}$. Изобразите результат на графике, по оси абсцисс отложите $i$ (номер измерения), а по оси ординат $x_i/\tilde x$. Можно ли определить состояние системы по этому графику? Каким выбрать параметр $N$?

In [ ]:
#your code here

2. (0.7 Баллов) Попробуем теперь вычислить вероятность нахождения системы в состоянии $A$ при условии проведенных измерений. Вероятность после первого измерения выражается с помощью формулы Байеса как
\begin{equation}
  P(A\ |\ x_1) = \frac{P(x_1\ |\ A) P(A)}{P(x_1)}, \quad P(x_1) = P(x_1\ |\ A) P(A) + P(x_1\ |\ B) P(B).
\end{equation}
В соответствии с этими формулами мы можем обновлять наше знание о вероятности нахождения системы в состоянии $A$ и $B$. В начале следующего шага $P(A) = P(A\ |\ x_1)$, $P(B) = 1 - P(A\ |\ x_1)$ и нам нужно будет учесть аналогичным образом уже измерение $x_2$, чтобы получить обновленнные вероятности. Постройте график $P(A)$ в зависимости от номера шага и прокомментируйте его. Подберите хорошее значение для параметра $N$, объясните свой выбор. Сравните результаты с первым пунктом.

In [ ]:
#your code here